version: "3"
services:
  springboot-service:
    image: 816595672718.dkr.ecr.ap-northeast-2.amazonaws.com/bodycheck/springboot:latest
    environment:
      - AWS_DB_PASSWORD=${AWS_DB_PASSWORD}
      - AWS_DB_URL=${AWS_DB_URL}
      - AWS_DB_USERNAME=${AWS_DB_USERNAME}
      - AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID}
      - AWS_S3_SECRET_ACCESS_KEY_ID=${AWS_S3_SECRET_ACCESS_KEY_ID}
      - DOMAIN=${DOMAIN}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_REDIRECT_URL=${KAKAO_REDIRECT_URL}
      - KAKAO_SECRET_KEY=${KAKAO_SECRET_KEY}
      - KAKAO_CID=${KAKAO_CID}
      - PROFILE_ACTIVE=${PROFILE_ACTIVE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_SSL_ENABLED=${REDIS_SSL_ENABLED}
      - MAIL_EMAIL=${MAIL_EMAIL}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8080:8080"

  nginx-service:
    image: 816595672718.dkr.ecr.ap-northeast-2.amazonaws.com/bodycheck/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - springboot-service
