spring:
  datasource:
    url: ${aws.db.url}
    username: ${aws.db.username}
    password: ${aws.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create # update / create
        default_batch_fetch_size: 1000

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 300MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.email}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          debug: true
          connectiontimeout: 1000
          auth: true
        starttls:
            enable: true

  kakao:
    client_id: ${kakao.client.id}
    redirect_uri: ${kakao.redirect.url}

  google:
    client_id: ${google.client.id}
    client_secret: ${google.client.secret}
    redirect_uri: ${google.redirect.url}

jwt:
  secret: ${jwt.secret}